// ============================================================
// E-Bike BNPL Platform - Mock Data
// ============================================================
import { Bike, User, LoanApplication, Order, Repayment, Guarantor, AuditLog, DashboardStats } from './types';

// ---- Mock Bikes ----
export const mockBikes: Bike[] = [
    {
        id: 'bike-001',
        name: 'DandoEv Pro 3000',
        brand: 'DandoEv',
        model: 'VS-3000',
        description: 'The DandoEv Pro 3000 is a high-performance electric commuter bike designed for Nigerian roads. With its powerful 3000W motor and long-range 60V battery, it handles city traffic and highway commutes with ease.',
        price: 1500000,
        images: ['/bikes/dando-ev-pro.jpg'],
        category: 'Commuter',
        motorPower: 3000,
        batteryCapacity: 2400,
        range: 120,
        topSpeed: 80,
        weight: 85,
        chargingTime: 4,
        warranty: '2 Years',
        color: ['Midnight Black', 'Electric Blue', 'Pearl White'],
        availability: 'in_stock',
        bnplEligible: true,
        bnplMinDownPayment: 0,
        stockQuantity: 15,
        rating: 4.8,
        reviewCount: 124,
        features: ['Regenerative Braking', 'LCD Dashboard', 'USB Charging Port', 'Anti-theft Alarm', 'LED Headlights', 'Tubeless Tyres'],
        createdAt: '2025-12-01T00:00:00Z',
        updatedAt: '2026-01-15T00:00:00Z',
    },
    {
        id: 'bike-002',
        name: 'DandoEv City 1500',
        brand: 'DandoEv',
        model: 'ER-1500',
        description: 'Perfect for daily commuting in Lagos, Abuja, and other major cities. The DandoEv City 1500 balances affordability with reliability.',
        price: 1500000,
        images: ['/bikes/dando-ev-pro.jpg'],
        category: 'Commuter',
        motorPower: 1500,
        batteryCapacity: 1200,
        range: 80,
        topSpeed: 55,
        weight: 65,
        chargingTime: 3,
        warranty: '1 Year',
        color: ['Forest Green', 'Sunset Orange', 'Silver'],
        availability: 'in_stock',
        bnplEligible: true,
        bnplMinDownPayment: 25,
        stockQuantity: 28,
        rating: 4.5,
        reviewCount: 89,
        features: ['Digital Speedometer', 'Disc Brakes', 'Storage Compartment', 'Kickstand', 'LED Tail Light'],
        createdAt: '2025-11-15T00:00:00Z',
        updatedAt: '2026-01-20T00:00:00Z',
    },
    {
        id: 'bike-003',
        name: 'ThunderBolt Sport X',
        brand: 'DandoEv',
        model: 'TB-SX',
        description: 'For the thrill-seekers. The ThunderBolt Sport X combines raw power with sporty aesthetics. Its 5000W motor delivers exhilarating acceleration while maintaining impressive range. Race-inspired design with premium components.',
        price: 1250000,
        images: ['/bikes/thunderbolt-sport.jpg'],
        category: 'Sports',
        motorPower: 5000,
        batteryCapacity: 3600,
        range: 150,
        topSpeed: 110,
        weight: 95,
        chargingTime: 5,
        warranty: '3 Years',
        color: ['Racing Red', 'Carbon Black', 'Neon Yellow'],
        availability: 'in_stock',
        bnplEligible: true,
        bnplMinDownPayment: 25,
        stockQuantity: 8,
        rating: 4.9,
        reviewCount: 67,
        features: ['Sport Suspension', 'Racing Seat', 'Digital Dashboard', 'GPS Tracker', 'Immobilizer', 'Dual Disc Brakes', 'Alloy Wheels'],
        createdAt: '2025-12-10T00:00:00Z',
        updatedAt: '2026-02-01T00:00:00Z',
    },
    {
        id: 'bike-004',
        name: 'CargoMax E-600',
        brand: 'DandoEv',
        model: 'CM-600',
        description: 'Built for business. The CargoMax E-600 is a heavy-duty electric cargo bike designed for logistics and delivery operations. With a massive cargo capacity and rugged build, it is the perfect solution for last-mile delivery in Nigeria.',
        price: 680000,
        images: ['/bikes/cargomax.jpg'],
        category: 'Cargo',
        motorPower: 2000,
        batteryCapacity: 2800,
        range: 90,
        topSpeed: 45,
        weight: 120,
        chargingTime: 6,
        warranty: '2 Years',
        color: ['Industrial Grey', 'Safety Orange'],
        availability: 'in_stock',
        bnplEligible: true,
        bnplMinDownPayment: 20,
        stockQuantity: 12,
        rating: 4.6,
        reviewCount: 45,
        features: ['200kg Cargo Capacity', 'Reinforced Frame', 'Wide Tyres', 'Cargo Box Included', 'Hydraulic Brakes', 'Side Mirrors'],
        createdAt: '2025-11-20T00:00:00Z',
        updatedAt: '2026-01-25T00:00:00Z',
    },
    {
        id: 'bike-005',
        name: 'SwiftFold Compact',
        brand: 'DandoEv',
        model: 'SF-C',
        description: 'The ultimate urban companion. The SwiftFold Compact folds in seconds for easy storage and transport. Perfect for apartment dwellers and those who combine e-bike rides with public transit.',
        price: 380000,
        images: ['/bikes/swiftfold.jpg'],
        category: 'Folding',
        motorPower: 1000,
        batteryCapacity: 800,
        range: 60,
        topSpeed: 40,
        weight: 28,
        chargingTime: 2.5,
        warranty: '1 Year',
        color: ['Sky Blue', 'Coral Pink', 'Graphite'],
        availability: 'in_stock',
        bnplEligible: true,
        bnplMinDownPayment: 20,
        stockQuantity: 20,
        rating: 4.3,
        reviewCount: 56,
        features: ['Foldable Frame', 'Lightweight', 'Removable Battery', 'Carry Handle', 'LED Lights', 'Phone Mount'],
        createdAt: '2026-01-05T00:00:00Z',
        updatedAt: '2026-02-05T00:00:00Z',
    },
    {
        id: 'bike-006',
        name: 'TrailBlazer Off-Road',
        brand: 'DandoEv',
        model: 'TB-OR',
        description: 'Conquer any terrain. The TrailBlazer Off-Road features knobby tyres, full suspension, and a powerful motor for adventurous riders who want to explore beyond paved roads.',
        price: 980000,
        images: ['/bikes/trailblazer.jpg'],
        category: 'Off-Road',
        motorPower: 4000,
        batteryCapacity: 3000,
        range: 100,
        topSpeed: 70,
        weight: 105,
        chargingTime: 5,
        warranty: '2 Years',
        color: ['Camo Green', 'Desert Sand', 'Matte Black'],
        availability: 'pre_order',
        bnplEligible: true,
        bnplMinDownPayment: 30,
        stockQuantity: 0,
        rating: 4.7,
        reviewCount: 32,
        features: ['Full Suspension', 'Knobby Tyres', 'Skid Plate', 'High Ground Clearance', 'Mud Guards', 'Crash Bars'],
        createdAt: '2026-01-10T00:00:00Z',
        updatedAt: '2026-02-08T00:00:00Z',
    },
];

// ---- Mock Users ----
export const mockUsers: User[] = [
    {
        id: 'user-001',
        email: 'adebayo.johnson@email.com',
        phone: '08012345678',
        firstName: 'Adebayo',
        lastName: 'Johnson',
        passwordHash: '$2a$10$mock',
        role: 'customer',
        customerStatus: 'active_bnpl',
        kycStatus: 'verified',
        dateOfBirth: '1992-05-15',
        address: '24 Sandstrip, Oworoshoki',
        state: 'Lagos',
        city: 'Lagos',
        employmentStatus: 'Employed (Full-time)',
        monthlyIncome: 350000,
        employerName: 'TechCorp Nigeria Ltd',
        employerAddress: '10 Marina Road, Victoria Island, Lagos',
        bvn: '22345678901',
        bankName: 'Guaranty Trust Bank',
        bankAccountNumber: '0123456789',
        bankAccountName: 'Adebayo Johnson',
        isEmailVerified: true,
        isPhoneVerified: true,
        twoFactorEnabled: false,
        createdAt: '2025-10-15T09:00:00Z',
        updatedAt: '2026-01-20T14:30:00Z',
        lastLoginAt: '2026-02-10T08:00:00Z',
    },
    {
        id: 'user-002',
        email: 'chioma.okafor@email.com',
        phone: '09098765432',
        firstName: 'Chioma',
        lastName: 'Okafor',
        passwordHash: '$2a$10$mock',
        role: 'customer',
        customerStatus: 'bnpl_applicant',
        kycStatus: 'pending',
        dateOfBirth: '1995-08-22',
        address: '15 Ahmadu Bello Way',
        state: 'FCT Abuja',
        city: 'Abuja',
        employmentStatus: 'Self-employed',
        monthlyIncome: 250000,
        employerName: 'Self',
        bvn: '33456789012',
        bankName: 'Access Bank',
        bankAccountNumber: '9876543210',
        bankAccountName: 'Chioma Okafor',
        isEmailVerified: true,
        isPhoneVerified: true,
        twoFactorEnabled: false,
        createdAt: '2026-01-05T10:00:00Z',
        updatedAt: '2026-02-08T11:00:00Z',
        lastLoginAt: '2026-02-09T16:00:00Z',
    },
    {
        id: 'user-003',
        email: 'emeka.nnamdi@email.com',
        phone: '07012349876',
        firstName: 'Emeka',
        lastName: 'Nnamdi',
        passwordHash: '$2a$10$mock',
        role: 'customer',
        customerStatus: 'registered',
        kycStatus: 'pending',
        dateOfBirth: '1988-03-10',
        address: '8 Aba Road',
        state: 'Rivers',
        city: 'Port Harcourt',
        employmentStatus: 'Business Owner',
        monthlyIncome: 500000,
        isEmailVerified: true,
        isPhoneVerified: false,
        twoFactorEnabled: false,
        createdAt: '2026-02-01T08:00:00Z',
        updatedAt: '2026-02-01T08:00:00Z',
    },
    {
        id: 'admin-001',
        email: 'admin@dandoev.ng',
        phone: '08000000001',
        firstName: 'System',
        lastName: 'Admin',
        passwordHash: '$2a$10$mock',
        role: 'super_admin',
        customerStatus: 'registered',
        kycStatus: 'verified',
        isEmailVerified: true,
        isPhoneVerified: true,
        twoFactorEnabled: true,
        createdAt: '2025-01-01T00:00:00Z',
        updatedAt: '2025-01-01T00:00:00Z',
    },
];

// ---- Mock Loan Applications ----
export const mockLoans: LoanApplication[] = [
    {
        id: 'loan-001',
        userId: 'user-001',
        userName: 'Adebayo Johnson',
        userEmail: 'adebayo.johnson@email.com',
        bikeId: 'bike-001',
        bikeName: 'VoltStorm Pro 3000',
        bikePrice: 850000,
        downPayment: 212500,
        loanAmount: 637500,
        interestRate: 15,
        serviceFee: 19125,
        tenure: 12,
        monthlyRepayment: 57624,
        totalRepayable: 691488,
        status: 'active',
        riskScore: 82,
        kycVerified: true,
        guarantorId: 'guar-001',
        guarantorVerified: true,
        approvedBy: 'admin-001',
        approvedAt: '2025-11-01T12:00:00Z',
        disbursedAt: '2025-11-02T09:00:00Z',
        documents: [],
        createdAt: '2025-10-20T10:00:00Z',
        updatedAt: '2026-02-01T00:00:00Z',
    },
    {
        id: 'loan-002',
        userId: 'user-002',
        userName: 'Chioma Okafor',
        userEmail: 'chioma.okafor@email.com',
        bikeId: 'bike-002',
        bikeName: 'EcoRider City 1500',
        bikePrice: 450000,
        downPayment: 112500,
        loanAmount: 337500,
        interestRate: 15,
        serviceFee: 10125,
        tenure: 6,
        monthlyRepayment: 59201,
        totalRepayable: 355206,
        status: 'pending',
        riskScore: 65,
        kycVerified: false,
        guarantorVerified: false,
        documents: [],
        createdAt: '2026-02-08T11:00:00Z',
        updatedAt: '2026-02-08T11:00:00Z',
    },
    {
        id: 'loan-003',
        userId: 'user-003',
        userName: 'Emeka Nnamdi',
        userEmail: 'emeka.nnamdi@email.com',
        bikeId: 'bike-003',
        bikeName: 'ThunderBolt Sport X',
        bikePrice: 1250000,
        downPayment: 312500,
        loanAmount: 937500,
        interestRate: 15,
        serviceFee: 28125,
        tenure: 18,
        monthlyRepayment: 58456,
        totalRepayable: 1052208,
        status: 'under_review',
        riskScore: 75,
        kycVerified: true,
        guarantorId: 'guar-002',
        guarantorVerified: true,
        documents: [],
        createdAt: '2026-02-05T14:00:00Z',
        updatedAt: '2026-02-09T10:00:00Z',
    },
];

// ---- Mock Repayments ----
export const mockRepayments: Repayment[] = [
    { id: 'rep-001', loanId: 'loan-001', userId: 'user-001', installmentNumber: 1, amount: 57624, amountPaid: 57624, dueDate: '2025-12-02', paidDate: '2025-12-01', status: 'paid', lateFee: 0, retryCount: 0, createdAt: '2025-11-02T00:00:00Z' },
    { id: 'rep-002', loanId: 'loan-001', userId: 'user-001', installmentNumber: 2, amount: 57624, amountPaid: 57624, dueDate: '2026-01-02', paidDate: '2026-01-02', status: 'paid', lateFee: 0, retryCount: 0, createdAt: '2025-11-02T00:00:00Z' },
    { id: 'rep-003', loanId: 'loan-001', userId: 'user-001', installmentNumber: 3, amount: 57624, amountPaid: 57624, dueDate: '2026-02-02', paidDate: '2026-02-03', status: 'paid', lateFee: 1152, retryCount: 0, createdAt: '2025-11-02T00:00:00Z' },
    { id: 'rep-004', loanId: 'loan-001', userId: 'user-001', installmentNumber: 4, amount: 57624, amountPaid: 0, dueDate: '2026-03-02', status: 'upcoming', lateFee: 0, retryCount: 0, createdAt: '2025-11-02T00:00:00Z' },
    { id: 'rep-005', loanId: 'loan-001', userId: 'user-001', installmentNumber: 5, amount: 57624, amountPaid: 0, dueDate: '2026-04-02', status: 'upcoming', lateFee: 0, retryCount: 0, createdAt: '2025-11-02T00:00:00Z' },
    { id: 'rep-006', loanId: 'loan-001', userId: 'user-001', installmentNumber: 6, amount: 57624, amountPaid: 0, dueDate: '2026-05-02', status: 'upcoming', lateFee: 0, retryCount: 0, createdAt: '2025-11-02T00:00:00Z' },
];

// ---- Mock Guarantors ----
export const mockGuarantors: Guarantor[] = [
    {
        id: 'guar-001',
        loanApplicationId: 'loan-001',
        applicantUserId: 'user-001',
        fullName: 'Oluwaseun Johnson',
        email: 'oluwaseun.j@email.com',
        phone: '08098765432',
        relationship: 'Sibling',
        status: 'accepted',
        acceptedAt: '2025-10-25T14:00:00Z',
        createdAt: '2025-10-22T10:00:00Z',
    },
    {
        id: 'guar-002',
        loanApplicationId: 'loan-003',
        applicantUserId: 'user-003',
        fullName: 'Ngozi Eze',
        email: 'ngozi.eze@email.com',
        phone: '09087654321',
        relationship: 'Colleague',
        status: 'accepted',
        acceptedAt: '2026-02-07T16:00:00Z',
        createdAt: '2026-02-06T09:00:00Z',
    },
];

// ---- Mock Orders ----
export const mockOrders: Order[] = [
    {
        id: 'ord-001',
        userId: 'user-001',
        bikeId: 'bike-001',
        bikeName: 'VoltStorm Pro 3000',
        bikeImage: '/bikes/voltstorm-pro.jpg',
        quantity: 1,
        unitPrice: 850000,
        totalAmount: 850000,
        paymentMethod: 'bnpl',
        status: 'delivered',
        deliveryAddress: '24 Sandstrip, Oworoshoki',
        deliveryCity: 'Lagos',
        deliveryState: 'Lagos',
        deliveryPhone: '08012345678',
        trackingNumber: 'VR-TRK-001234',
        loanId: 'loan-001',
        createdAt: '2025-10-20T10:00:00Z',
        updatedAt: '2025-11-05T14:00:00Z',
    },
];

// ---- Mock Audit Logs ----
export const mockAuditLogs: AuditLog[] = [
    { id: 'log-001', userId: 'admin-001', userName: 'System Admin', action: 'APPROVE_LOAN', resource: 'loan', resourceId: 'loan-001', details: 'Approved BNPL application for VoltStorm Pro 3000', ipAddress: '192.168.1.1', timestamp: '2025-11-01T12:00:00Z' },
    { id: 'log-002', userId: 'user-002', userName: 'Chioma Okafor', action: 'SUBMIT_APPLICATION', resource: 'loan', resourceId: 'loan-002', details: 'Submitted BNPL application for EcoRider City 1500', ipAddress: '10.0.0.1', timestamp: '2026-02-08T11:00:00Z' },
    { id: 'log-003', userId: 'user-003', userName: 'Emeka Nnamdi', action: 'SUBMIT_APPLICATION', resource: 'loan', resourceId: 'loan-003', details: 'Submitted BNPL application for ThunderBolt Sport X', ipAddress: '10.0.0.2', timestamp: '2026-02-05T14:00:00Z' },
    { id: 'log-004', userId: 'user-001', userName: 'Adebayo Johnson', action: 'MAKE_PAYMENT', resource: 'repayment', resourceId: 'rep-003', details: 'Payment for installment #3 - Late fee applied', ipAddress: '10.0.0.3', timestamp: '2026-02-03T09:30:00Z' },
    { id: 'log-005', userId: 'admin-001', userName: 'System Admin', action: 'UPDATE_BIKE', resource: 'bike', resourceId: 'bike-006', details: 'Updated TrailBlazer availability to pre-order', ipAddress: '192.168.1.1', timestamp: '2026-02-08T15:00:00Z' },
];

// ---- Mock Dashboard Stats ----
export const mockDashboardStats: DashboardStats = {
    totalUsers: 1247,
    activeLoans: 89,
    totalRevenue: 45680000,
    bikesInStock: 83,
    pendingApplications: 12,
    defaultRate: 3.2,
    monthlyRevenue: [
        { month: 'Sep', revenue: 3200000, loans: 8 },
        { month: 'Oct', revenue: 4500000, loans: 12 },
        { month: 'Nov', revenue: 5800000, loans: 15 },
        { month: 'Dec', revenue: 7200000, loans: 18 },
        { month: 'Jan', revenue: 6100000, loans: 14 },
        { month: 'Feb', revenue: 4800000, loans: 11 },
    ],
    loansByStatus: [
        { status: 'Active', count: 89 },
        { status: 'Pending', count: 12 },
        { status: 'Completed', count: 156 },
        { status: 'Defaulted', count: 8 },
        { status: 'Rejected', count: 23 },
    ],
    topBikes: [
        { name: 'VoltStorm Pro', sales: 45 },
        { name: 'EcoRider City', sales: 38 },
        { name: 'CargoMax E-600', sales: 28 },
        { name: 'SwiftFold', sales: 22 },
        { name: 'ThunderBolt', sales: 18 },
    ],
    recentActivity: [],
};
